### ISSUE TITLE
FormFlowEvents::POST_BIND_SAVED_DATA

### ISSUE THREAD

**Issue by AlexSanzharevskyy** [craue/CraueFormFlowBundle#124]
Hi!
I have a flow. Step №2 has a checkbox, like Add Driver in the CraueFormFlowBundle
Demo. But, when i try to do something with data:
if ($event->getStepNumber() === 2) {

}
it doesn't work for me. it fires, after i refresh the page.

**Comment by timbordemann** [comment]
I encounter the same problem.

To illustrate it, I have created a repo with a sample app: https://github.com/timbordemann/form_flow_event_example
The form flow in the sample app needs to create a new membership entity based on a given group invitation between step 1 and step 2. In step 2 the user has to choose an email address out of a predefined pool of email addresses and assign it to the membership.

If I understand the documentation correctly, the PostBindSavedData event should be fired after each step and for each step. The form flow bundle seems to trigger the event only after the last step though. All the other events also don't work. Do I miss something?
