### ISSUE TITLE
appDevDebugProjectContainer.php line 309

### ISSUE THREAD

**Issue by ciscorojo** [craue/CraueFormFlowBundle#136]
Hi , i'm trying to install your bundle in acme and i followed  your example (first method) but i received this error message :
appDevDebugProjectContainer.php line 309.
I've definiend the forms, generated the entites ( vehicle ) and i 've been set the services.

I forget something?
Tnx
Cisco
.

**Comment by TiFullPay** [comment]
Attempted to load class "LoginEntryPoint" from namespace "UsuarioBundle\Services\EventListener".
Did you forget a "use" statement for another namespace?
500 Internal Server Error - ClassNotFoundException

Stack Trace





in app/cache/dev/appDevDebugProjectContainer.php at line 1377  -
     */
    protected function getFbnUser_LoginEntryPointService()
    {
        return $this->services['fbn_user.login_entry_point'] = new \UsuarioBundle\Services\EventListener\LoginEntryPoint($this->get('router'));
    }
    /**
