### ISSUE TITLE
Save FormFlow status for end later, it's possible?

### ISSUE THREAD

**Issue by reypm** [craue/CraueFormFlowBundle#152]
I'll start to use this Bundle in one of my developments but have some doubts around the usage. My development require a weird feature and it's save form data at any step or position where user leave so user can come back and restart the flow exactly where it leaves, is that possible with this Bundle? If so, any example?

**Comment by sujayjaju** [comment]
Is DoctrineStorage the way to go here?
Any pointers on how to use it?

**Comment by StephenOTT** [comment]
@sujayjaju did you get this working?

**Comment by sujayjaju** [comment]
@StephenOTT Yes - the trick is to use DoctrineStorage and then save `$flow->getInstanceId()` against the user.  Eg:
````php
        $flow->bind($formData);
        if($id == 0){
            $instanceId = $this->getUser()->getNewListingInstanceId();
            if(!$instanceId){
                $this->getUser()->setNewListingInstanceId($flow->getInstanceId());
                $em = $this->getDoctrine()->getManager();
                $em->persist($this->getUser());
                $em->flush();
            }
        }
````

Then, to resume, go to FORM_URL?instance=SAVED_INSTANCE_ID 
````twig
<a href="{{ path('create_listing') }}?step=2&instance={{ app.user.newListingInstanceId }}"
                       class="button btn-add-new no-margin">Complete Your Listing</a>
````

It is important to clear the doctrine storage when the user is done with the final submission.
````php
    //Clear Doctrine Storage
    $flow->getDataManager()->drop($flow);
