### ISSUE TITLE
Flow with steps skipped according to database values

### ISSUE THREAD

**Issue by asoupper** [craue/CraueFormFlowBundle#160]
I have trouble to figure out how to implement my workflow.
Could you please help me to understand how to do this cleanly?

Let's imagine this scenario (it's an over simplification of my needs ;) ):
1. Step 1: choose a company (from a list in database)
2. Step 2: choose one of the contacts working for this company (contacts are available in the database). Step may be skipped if only one contact is available for the selected company
3. Step 3: choose one address of the contact's addresses (addresses are in the db). Step may be skipped if only one address is available for the selected contact.

Could you explain me how to organize my code to do this?

Thanks
Alban

**Comment by craue** [comment]
Skipping the steps would be easy, but directly setting those values would not. Also, it could be problematic if a new contact or a new address is added to the database while you're in e.g. step 4 and there's now more than just one choice which could be set directly.
An easier approach would be to preselect a value but still let the user submit the form:

```php
public function createWhateverAction() {
	$formData = new Whatever();
	
	$flow = $this->get('myCompany.form.flow.createWhatever');
	$flow->bind($formData);

	$form = $flow->createForm();
	if ($flow->isValid($form)) {
		$flow->saveCurrentStepData($form);

		if ($flow->nextStep()) {
			if ($flow->getCurrentStepNumber() === 2 && $companyHasOnlyOneContact) {
				// preselect contact
				$formData->setContact($onlyAvailableContactForCompany);
			}
			
			if ($flow->getCurrentStepNumber() === 3 && $contactHasOnlyOneAddress) {
				// preselect address
				$formData->setAddress($onlyAvailableAddressForContact);
			}
			
			$form = $flow->createForm();
		} else {
			// done

			return $this->redirect($this->generateUrl('home'));
		}
	}

	return $this->render('MyCompanyMyBundle:Whatever:createWhatever.html.twig', array(
		'form' => $form->createView(),
		'flow' => $flow,
	));
}
```
