### ISSUE TITLE
Start button

### ISSUE THREAD

**Issue by mohamedhamad** [craue/CraueFormFlowBundle#161]
Is there a way to change the text of the first next button to say something like "Start" or "Begin" instead of next?

**Comment by webdevilopers** [comment]
BTW @craue is there a way to change the "Next" Button Label with overriding the complete template? Since there is a `label` option for steps inside the `loadStepsConfig` method maybe there should be an option to access the `label` or `button` itself?

**Comment by craue** [comment]
@webdevilopers: This wouldn't work in each case, e.g. when steps are skipped you cannot know which one will be the next.

**Comment by webdevilopers** [comment]
Ok. Should we add your example in https://github.com/craue/CraueFormFlowBundle/issues/72 to the "advanced" docs?

**Comment by craue** [comment]
@webdevilopers: If at all, seems like #114 would fit better.

**Comment by webdevilopers** [comment]
Ok! Close @mohamedhamad ?

**Comment by craue** [comment]
This is now easily possible due to #226.
