### ISSUE TITLE
Approach B multi form & multi form data class (entity)

### ISSUE THREAD

**Issue by eddiejaoude** [craue/CraueFormFlowBundle#162]
In **Approach B** under [Create Action](https://github.com/craue/CraueFormFlowBundle/blob/master/README.md#create-an-action)

The first line the instantiation of `Vehicle` class, but this class is not defined? 

Each **step / form** has its own **form data class**, how to make the **form data class** dynamic & change with the current step? It only works for the first step, but fails on any other step at the moment.

```php
$formData = new Vehicle(); // Your form data class. Has to be an object, won't work properly with an array.
```

**Comment by craue** [comment]
The `Vehicle` class is just meant as a placeholder in that example. Of course you have to define your own entity (or form data) classes fitting your use cases. Not providing this class was done on purpose, hence the comment on that line. But if you really want to take a look at that file, there's one in [CraueFormFlowDemoBundle](https://github.com/craue/CraueFormFlowDemoBundle). Just as a side note, the section "Create an action" is not tied to a specific approach.

For the other issue, refer to #28.
