### ISSUE TITLE
Form with multiple Entities

### ISSUE THREAD

**Issue by birdnestman** [craue/CraueFormFlowBundle#167]
First of all: Thank you for this bundle.

I have an issue with a form. I use 3 Entities, for each page another.
Everything seems to be work, but if i click on finish, an error appears. 

> An exception occurred while executing 'INSERT INTO Insurance (nsr_cover, nsr_bonus_cover, 
> nsr_xenon, nsr_parking_harm, nsr_baggage, nsr_occupants, nsr_help_point_plus, nsr_comment)
> VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null, null, null]:

I think the error could be by binding the entities to the form.

```php
class CreateInsReqFlow extends FormFlow
{
    protected function loadStepsConfig()
    {
        return array(
            array(
                'label' => 'person',
                'type' => new PersonType(),
            ),
            array(
                'label' => 'vehicle',
                'type' => new VehicleType(),
            ),
            array(
                'label' => 'insurance',
                'type' => new InsuranceType(),
            ),
            array(
                'label' => 'confirmation',
            )
        );
    }
    public function getName()
    {
        return 'createInsuranceRequest';
    }
}
```

```php
class InsuranceRequestController extends Controller
{
    public function newAction(Request $request)
    {
        $formData['person'] = new Person();
        $formData['vehicle'] = new Vehicle();
        $formData['insurance'] = new Insurance();

        $flow = $this->get('nuvox.form.flow.createInsReq');

        $flow->bind($formData);

        $form = $flow->createForm();

        if($flow->isValid($form)){
            $flow->saveCurrentStepData($form);

            if ($flow->nextStep()) {

                // form for the next step
                $form = $flow->createForm();
            } else {

                // flow finished
                $insuranceRequest = new InsuranceRequest();
                $person = $formData['person'];
                $vehicle = $formData['vehicle'];
                $insurance = $formData['insurance'];

                $em = $this->getDoctrine()->getManager();
                $em->persist($person);
                $em->persist($vehicle);
                $em->persist($insurance);

                $insuranceRequest->setPerson($person);
                $insuranceRequest->setVehicle($vehicle);
                $insuranceRequest->setInsurance($insurance);

                $em->persist($insuranceRequest);
                $em->flush();

                $flow->reset(); // remove step data from the session

                return $this->redirect($this->generateUrl('home')); // redirect when done
            }
        }

        return $this->render('NuvoxMyBundle:Form:CreateInsReqFlow.html.twig', array(
                'form' => $form->createView(),
                'flow' => $flow,
            ));
    }
}
```

Thank you for any help.

**Comment by craue** [comment]
Create a dedicated form data class containing your entities. Or maybe you can just use your `InsuranceRequest` for that. See #28.

**Comment by birdnestman** [comment]
I found the issue. i forgot to register the form also as service and link it to the flow. spent so many hours to find the issue. Thank you anyway for help and for this great bundle!

**Comment by tejac** [comment]
I apologize for re-opening the issue, but I would really appreciate some help.
@birdnestman, I am trying to create a similar thing with the form flow and multiple entities in it. My code is basically the same as yours, but I am stuck on how to access the corresponding entity to each step (i.e. form type). The data bound to the form is the whole array `$formData`, which results in wrong type of form view data (an array instead of an instance of the class). How did you "select" the right entity (Person/Vehicle/Insurance) from the array `$formData` to then display it in the form flow? Maybe it's something trivial I overlooked, I can't seem to find a (right) way.
Thank you in advance. :)

**Comment by birdnestman** [comment]
Hey, sorry for the late reply... I'm not sure if I understand it right, but i will share my code with you.

```php
class CreateInsReqFlow extends FormFlow
{
    protected $formType;

    protected $allowDynamicStepNavigation = true;

    public function setFormType(FormTypeInterface $formType) {
        $this->formType = $formType;
    }

    protected function loadStepsConfig()
    {
        return array(
            array(
                'label' => 'Person',
                'type' => $this->formType,
            ),
            array(
                'label' => 'Fahrzeug',
                'type' => $this->formType,
            ),
            array(
                'label' => 'Versicherung',
                'type' => $this->formType,
            ),
        );
    }
    public function getName()
    {
        return 'createInsuranceRequest';
    }
}
```

**Comment by andreybolonin** [comment]
@birdnestman 

Can you show all worked code with multiple entities and multiple steps?
Controller, Entities, FormTypes, services.yml, etc.

Very big thanks :)

**Comment by olivier1208** [comment]
Hey i'm having a big mess with that.
I'm trying to use the @andreybolonin Approach C but i also have to dynamically generate data into a form (like Subcategories populated from Categories)
Anyone who did that ??
