### ISSUE TITLE
Multiple step form with multiple entities

### ISSUE THREAD

**Issue by sndpnits** [craue/CraueFormFlowBundle#168]
Does this bundle support multiple step form using different entities?
I have two entities and two different form type for both, I want to use first entity in first step and the second one in second step. But I can see we can pass only one class(form data) to the controller.

**Comment by craue** [comment]
See #28.

**Comment by sndpnits** [comment]
Thank You!!  It worked. :)

**Comment by craue** [comment]
:smirk:

**Comment by sndpnits** [comment]
$em = $this->getDoctrine()->getManager();
        $order = new Orders();
        $address= $em->getRepository('IServiceAppBundle:Address')->findOneBy(array('user' =>    $this->getUser()));
        
        $formData['order'] = $order;
        $formData['address'] = $address;

        $flow = $this->get('craue_order.form.flow.createOrder'); // must match the flow's service id
        $flow->bind($formData);

        // form of the current step
        $form = $flow->createForm();
        $flow->saveCurrentStepData($form);
        if ($flow->isValid($form)) {
            $flow->saveCurrentStepData($form);

            if ($flow->nextStep()) {
                $form = $flow->createForm();
            } else {
                ladybug_dump($formData['order']);

                $em->persist($formData['order']);
                
                $em->persist($formData['address']);
                $em->flush();

                $flow->reset(); // remove step data from the session

                return $this->redirect($this->generateUrl('home')); // redirect when done
            }
        }

I tried to dump the $formData, but all the fields are empty. I checked with profiler, all the values are stored in session but  don't come in $formData. :(

**Comment by craue** [comment]
@sndpnits: What exactly is `$formData`? I don't see it being defined here. It should be an object, not an array. Also, you call `$flow->saveCurrentStepData($form)` twice.
