### ISSUE TITLE
Custom validation groups

### ISSUE THREAD

**Issue by AdamBoxall** [craue/CraueFormFlowBundle#170]
Given you can't define specific groups to validate on sub-types with `@Assert\Valid` [(see here)](https://github.com/symfony/symfony/issues/3622), validating them is a major hassle with having to follow the `flow_<formName>_step<stepNumber>` format.

It would be really helpful to be able to define some *additional* validation groups in the steps config:

    /**
     * {@inheritDoc}
     */
    protected function loadStepsConfig()
    {
        return array(
            array(
                'label' => 'delivery',
                'type' => new DeliveryType,
                'groups' => array('address')
            ),
            array(
                'label' => 'payment',
                'type' => new PaymentType,
                'groups' => array('address')
            )
        );
    }

That way my `AddressType` sub-type could simply define the assertions within an "address" group, and then when it's used in both the *delivery* (shipping address) and *payment* (billing address) steps, I don't have to define both the "flow_checkout_step1" and "flow_checkout_step2" validation groups.

**Comment by craue** [comment]
Could you have a close look at #172?

**Comment by AdamBoxall** [comment]
Thanks, that looks spot on. I'll give it a test over the next few days.
