### ISSUE TITLE
 Dynamically choose which steps to skip

### ISSUE THREAD

**Issue by dkasperski** [craue/CraueFormFlowBundle#176]
Hello. I`ve just started to use this bundle in my project and I wonder how to dynamically choose which step to skip. 

For example when in first step is only one select with 2 options to choice. Scenarios:

- first scenario ("normal"): step 1 - user pick option A -> step 2 - user type and submit his telephone -> step 3 user type his question and send whole form

- second scenario (dynamically apply skipping): step 1 - user pick option B -> step 3 user type his question and send whole form.

English is not my mother tongue, please excuse any errors on my part. Thanks in advance.

**Comment by craue** [comment]
Take a look at the demo bundle, there's https://github.com/craue/CraueFormFlowDemoBundle/blob/4bdee980ad0e00b4e8bab9735b0a7161619ca191/Form/CreateLocationFlow.php#L36 for example.
