### ISSUE TITLE
Add translation_domain to form flow for step labels

### ISSUE THREAD

**Issue by webdevilopers** [craue/CraueFormFlowBundle#177]
Is there a way to add a `translation_domain` to the form flow for the labels instead of using the `messages` domain?

https://github.com/craue/CraueFormFlowBundle#method-loadstepsconfig
**By default, the labels will be translated using the messages domain when rendered in Twig.**

Possibly related:
- https://github.com/craue/CraueFormFlowBundle/issues/67
- https://github.com/craue/CraueFormFlowBundle/issues/105

**Comment by craue** [comment]
There's no way to set a translation domain, but you could override the `stepList_customization.html.twig` template and redefine the `craue_flow_stepLabel` block:

```twig
{% extends 'CraueFormFlowBundle:FormFlow:stepList_content.html.twig' %}

{% block craue_flow_stepLabel %}
	{{- stepLabel | trans({}, 'whatever') -}}
{% endblock %}
```

Both mentioned issues are _not_ related. :smirk:
