### ISSUE TITLE
How do I manipulate the form data between steps?

### ISSUE THREAD

**Issue by Brainshack** [craue/CraueFormFlowBundle#181]
Hi,

between step 1 and 2 of my form flow, I need to manipulate the values of a form field, based on the input the user made in step 1. What would be the best way to do this?

I tried using events in the form and in the flow, but couldn't get anything to work. I also tried doing it in my controller, but am also having a hard time getting it to work.

What is the best way of achieving something like this?

**Comment by craue** [comment]
Did you take a look at the [demo code](https://github.com/craue/CraueFormFlowDemoBundle)?

**Comment by Brainshack** [comment]
Well I looked at it, but could find any example where you overwrite a property of the bound entity after a certain step. Am I overseeing something?

**Comment by craue** [comment]
I thought you want to render different values for a form field in step 2 based on user input from step 1, as it is done in the "create location" demo flow. Now this sounds different. Could you explain in more detail what exactly you're trying to do, maybe with an example?
