### ISSUE TITLE
Doctrine queries are shared across steps and always performed

### ISSUE THREAD

**Issue by webdevilopers** [craue/CraueFormFlowBundle#183]
I have a 3-step form, each step has some entity field types, step 3 doesn't have any at all. Excerpt:
```php
    public function buildForm(FormBuilderInterface $builder, array $options) {
        switch ($options['flow_step']) {
            case 1:
                $builder
                    ->add('scope', 'entity', array(
                        'required' => true,
                        'expanded' => true,
                        'class' => 'AppBundle:Scope',
                    ))
                    ->add('mounting_type', 'entity', array(
                        'required' => true,
                        'expanded' => true,
                        'class' => 'AppBundle:MountingType'
                    ))
                break;
            case 2:
                #...
                break;
            case 3:
                $builder
                    ->add('comment', 'textarea', array(
                    ))
                    ->add('captcha', 'captcha', array(
                    ))
                ;
                break;
        }
```

I checked the database profiler on each step. Every step will also include the the combined queries of the former steps.

Can we prevent this?

**Comment by craue** [comment]
Which version of the bundle are you using?

**Comment by craue** [comment]
Never mind, I thought about something different.
There's no way to avoid building the forms of previous steps because they're needed to progressively "fill" the data class, otherwise the data of previous steps would be lost.

**Comment by webdevilopers** [comment]
For my small form this isn't a performance problem.

Is there a way to lazy load choices in Doctrine?
* http://api.symfony.com/2.6/Symfony/Component/Form/Extension/Core/ChoiceList/LazyChoiceList.html
E.g. using Proxies?

**Comment by craue** [comment]
I don't see how lazy loading choices could change anything.
