### ISSUE TITLE
Strange error validation grouping in profiler and custom form_label template

### ISSUE THREAD

**Issue by webdevilopers** [craue/CraueFormFlowBundle#186]
I have a pretty basic 3-step form setup:
https://gist.github.com/webdevilopers/2f3eab2d8722c4dfd637

The elements for `validation_group` *flow_calculatorFlow_step1* are:
* scope
* mounting_type
* glass_type
* post_color

When I submit the form without entering any data my profiler shows me 4 errors but the are splitted.
*3* belong to the step while *1* (`scope`) is separeted:
![3_1_errors](https://cloud.githubusercontent.com/assets/3479626/8391200/8ead3518-1cb9-11e5-959e-3bd6d50db9af.png)

I am using a custom form template. This template is telling the `form_label` block to add a `has-error` class to the label when errors occur:
```twig
        {% if errors|length > 0 %}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' has-error')|trim}) %}
        {% endif %}
```

But this condition is only true with the *1* element `scope` that was separeted.
I also have a step 3 that has more fields but the same problem with a total of *3*:*1* elements:
![3_1_errors2](https://cloud.githubusercontent.com/assets/3479626/8391211/35089e3e-1cba-11e5-9d67-7b20c8cc1996.png)

Any idea what is happening here? Is it related to this bundle? Do I have to change some error bubbling config?
Or could it be twig or symfony related?

Possible related issue:
* https://github.com/craue/CraueFormFlowBundle/issues/157

**Comment by craue** [comment]
Could you already track down the issue? At least, template changes wouldn't influence validation, only rendering the error messages. Are you able to set up a failing test case? Or could you provide a symfony-standard fork to reproduce the issue?

**Comment by webdevilopers** [comment]
I will try to reproduce it with the `CraueFormFlowDemoBundle`. For my current project I will have to implement a workaround. So it will take some time until I have it tracked down.

**Comment by webdevilopers** [comment]
I currently have an issue here:
https://github.com/craue/CraueFormFlowBundle/issues/211

Somehow the first two steps have the same current step number **1**.

I also realized that on step **2** the properties on the entity are not populated with the values from the first form step.
On step **3** everything is correct and step **1** and **step2** form data was added.

It looks like that is my main problem. Is this a session issue maybe?
Did I forget to set a step number manually somewhere?

**Comment by webdevilopers** [comment]
Right now @craue I'm realizing something else looking at the Errors from the Symfony Profiler:
![3_1_errors2](https://cloud.githubusercontent.com/assets/3479626/8391211/35089e3e-1cba-11e5-9d67-7b20c8cc1996.png)

The 3 errors that do not show up in the template and that are not marked as errors in the left column like `scope`is all feature underscores e.g. `mounting_type` instead of the camel cased names in the right column list e.g. `mountingType`. THIS SEEMS TO BE THE ORIGINAL ISSUE!?

**Comment by webdevilopers** [comment]
Yes, this was the issue. The property inside the entity is e.g. `mountingType`.
In my form I used `mounting_type` - same inside my template.
Anyway Symfony would render the form correctly.

But when submitting the form without filling out these required fields,
the data transformer is unable to link the underscore naming with the camel case naming.

If someone is not aware of this being possible at all the profiler doesn't really point at it.
Bug or feature?
