### ISSUE TITLE
Dynamic Steps

### ISSUE THREAD

**Issue by aaronwardle** [craue/CraueFormFlowBundle#190]
Hi, 

First of all this is an awesome plugin :)

Is it possible to dynamically change the steps which are shown to the user for example we are looking to do this with around 15 steps in total but the user may only select 3 areas to fill out so ideally we would like them to see just 4 steps so that the process does not look too long. 

1. We ask the user for their contact details
2. We ask the user to select some categories they want to complete
3. Depending on select in 2) we will show up to 15 sub steps
4. Form Finish - Completion screen.

Any pointers on this would be much appreciated. 

Thanks Aaron

**Comment by craue** [comment]
Dynamically changing steps is not supported, but you can skip them.

**Comment by aaronwardle** [comment]
Thanks for the reply Christian, I'll have a think to see if there is something else I can do to reduce the steps or just not show them the main problem is there could be 40+ steps which gets reduced down to around 4/5 depending on users initial selection so I need to show a reduced list so users don't get put off with the large qty of steps. 

Thanks again Aaron

**Comment by craue** [comment]
You could try customizing the step list rendering to hide skipped steps, but 40 steps sounds pretty much. I hope there's no case where a user needs to face them all. :smirk:

Alternatively you could create several more specific flows and prepend a simple form to let the user choose which one to use.
