### ISSUE TITLE
Use `validation_groups` of the form type for the current step

### ISSUE THREAD

**Issue by ianfp** [craue/CraueFormFlowBundle#191]
I have a different form type for each step of my flow. The form type for the first step specifies custom validation groups in the `configureOptions()` method, but these seem to be ignored by the flow. Instead, I have to specify the validation groups in the flow class like so:

    protected function loadStepsConfig()
    {
        return [
            $this->step1(),
            $this->step2(),
        ];
    }

    private function step1()
    {
        return [
            'label' => 'step1',
            'form_type' => new Step1Type(),

            // Step1Type already defines these validation groups!
            'form_options' => [
                'validation_groups' => ['Default', 'some_custom_group'],
            ],
        ];
    }

While the new `form_options` setting in 3.0 is a major improvement over 2.x (keep up the good work!), it would be *excellent* if the flow defaulted to the validation groups defined in `Step1Type`. Is that possible?

Using Symfony 2.7.3 and CraueFormFlowBundle 3.0@dev.

**Comment by craue** [comment]
That's indeed not possible. `FormFlow::getFormOptions` sets a validation group for the current step of the flow, if none is defined already. The issue is that options defined in `configureOptions` are form-specific and not visible to the flow.

**Comment by ianfp** [comment]
Ok, I'm closing this issue.
