### ISSUE TITLE
Documentation guidance on how to use our own template

### ISSUE THREAD

**Issue by PeterFour** [craue/CraueFormFlowBundle#192]
It would be good to have a part in the documentation about how to overwrite the button or the step lists.
It should be standard twig but maybe there is a configuration on what template the Bundle is using.

**Comment by craue** [comment]
There's indeed nothing special. What exactly do you expect to be documented?

**Comment by PeterFour** [comment]
Well for example I would like to use the css that I have with this theme (http://webapplayers.com/inspinia_admin-v2.2/form_wizard.html) but wihout using jSteps because it looks like painful to setup

**Comment by craue** [comment]
I still don't know what should be documented for this. You can override the templates if needed. This is nothing bundle-specific.
