### ISSUE TITLE
Skipping validation of fields based on another field

### ISSUE THREAD

**Issue by Nairebis** [craue/CraueFormFlowBundle#194]
I'm relatively new at Symfony at general, just to establish that.

There has to be an easy way to do this, but I'm missing it. I have a radio button on my form that determines whether two other fields are checked for validation. The way the Symfony manual says to do this for simple one-page forms is to set a different validation group for the two fields and then have a function that returns the proper set of groups based on the data, something like so (from the Symfony manual):

        'validation_groups' => function (FormInterface $form) {
            $data = $form->getData();

            if (Client::TYPE_PERSON == $data->getType()) {
                return array('person');
            }

            return array('company');
        },

But FormFlow doesn't support passing a function for the validation_groups, it gets mangled into an array with the prefix+step number. But the FormFlow docs seemed to imply I should use getFormOptions(), so I tried something like this:

    public function getFormOptions($step, array $options = []) {
        $options = parent::getFormOptions($step, $options);
        $formData = $this->getFormData();
        $units = $formData->getNumberOfUnits();
        if ($units == 1) {
            $options['validation_groups'] = [ 'section1' ];
        }
        return $options;
    }

The problem is that the NumberOfUnits field doesn't have the just-submitted data at that point, it has previously submitted data, so it didn't work right.

To see if the dynamic Symfony-method worked, I changed the following in FormFlow.php line 730:

                } elseif ($options['validation_groups'] !== false && gettype($options['validation_groups']) !== 'object') {

That allowed me to pass in a function. At that level, I was able to use $form->getData(), which had the proper submitted data I could use to compute the proper validation groups. Something like this in my loadStepsConfig():

    2 => array(
        'label' => 'page2',
        'form_type' => new SignupType(),
        'form_options' => [
            'validation_groups' =>
                function(FormInterface $form) {
                    $data = $form->getData();
                    $units = $data->getNumberOfUnits();
                    if ($units == 1) {
                        return [ 'flow_ycc_signup_step2', 'section1' ];
                    }
                    return [ 'flow_ycc_signup_step2' ];
                }
        ),

I can do it that way, but I'd like to do it the "FormFlow approved" way. So how should this be done?

(Though, you probably should support passing in a function to validation_groups, since that's a Symfony feature).

Thanks,

Tim

**Comment by craue** [comment]
I've never had such a use case, but #196 should help with that.

**Comment by Nairebis** [comment]
Excellent, thank you!
