### ISSUE TITLE
Data class attributes modified inside controller do not save between steps.

### ISSUE THREAD

**Issue by CodyMurray** [craue/CraueFormFlowBundle#195]
I have a  form flow that I have been working on where most of the attributes in my data class need to be set based off information pulled from a remote XML file that is accessed from an api key submitted in step one.

Here is how my form is supposed to work.

Step one: User enters api key, on validation the controller runs some methods that I wrote to verify the validity of the api key, then sets the attribute values to the data class from information gathered via the remote xml file.

Step two: User selects which set of data from the xml that they want to use.

Step three: User fills out a few questions, then submits the form.

Basically, everything works other than saving the data pulled from the xml file between steps. I use print_r() to debug the dataclass between each step, from step one to step two, it populates the data class correctly but as soon as I hit next on step 2 it loads step 3, but the dataclass only holds the information entered directly in the form the stuff that I set manually doesn't stick.

I tried setting the data directly to the entity, as well as setting the data through the form, but either way it still doesn't save the data correctly.

Controller
```php
    public function indexAction()
    {
        $p = new ApplicationProcessor();
        $formData = new Application();

        $flow = $this->get('SCNCE.form.flow.newApplication');
        $flow->bind($formData);
        $form = $flow->createForm();
        if ($flow->isValid($form)){
            $p->handleEntity($formData, $flow);
            $flow->saveCurrentStepData($form);
            if($flow->nextStep()){
                $form = $flow->createForm();
            } else {
                $em = $this->getDoctrine()->getManager();
                $em->persist($formData);
                $em->flush();

                $flow->reset();

                return $this->redirectToRoute('application');
            }
        }
```
the handleEntity() method is just a switch statement that writes the data to the attributes from the XML data at each step.

EDIT: I figured that I might as well put the method in here as well. Right now It's using the form data to set the attributes, however my first attempt just set the values directly to the entity object (which I think is more efficient, anyways, right?) 
```php
public function handleEntity(Application $entity, FormFlow $flow){
        $step = $flow->getCurrentStep();
        $keyID = $entity->getApiKeyId();
        $vCode = $entity->getApiVerificationCode();
        switch($step){
            case 1:
                $api = new AccountApi($keyID, $vCode);
                $api->accountStatus();
                $api->apiKeyInfo();
                $data = $flow->getFormData();
                $data
                    ->setApiAccessMask($api->getAccessMask())
                    ->setApiType($api->getType())
                    ->setApiExpiry($api->getExpires())
                    ->setCharacterList($api->getCharacters())
                    ->setCharacterList($this->mergeCharacterSheet($entity));
                break;
            case 2:
                // TODO: Set entity attributes for character chosen in step 2 after saving problem is solved
                break;
            case 3:
                break;
            case 4:
                break;
        }
    }
```

**Comment by craue** [comment]
What you describe is actually the expected behavior. Only the submitted form data is saved when calling `$flow->saveCurrentStepData($form)`. Thus, data set on the entity directly is not taken into account.

It would be nice to save additional data, but I've not spent time yet to evaluate how that could be done.

To solve your issue, you'd need to set that data in each step (and probably cache the fetched XML content). You can, however, use the attached storage.
