### ISSUE TITLE
Modify formType with events

### ISSUE THREAD

**Issue by bilougit** [craue/CraueFormFlowBundle#202]
I need to fill some fields into my form, and it seems that the best way would be to use events of CraueFormFlowBundle. it'd be great if it's explained further in here https://github.com/craue/CraueFormFlowBundle#using-events btw.

I'd like to be able to get the form instance, to get some data from HttpFoundation\Request#request and  create a field into the form with what I retrieved from the Request.

Can you help me out with this please?

**Comment by craue** [comment]
Maybe all you need is building your form depending on a condition. Please read the documentation and take a look at the [demo bundle](https://github.com/craue/CraueFormFlowDemoBundle). If that still doesn't help, be more precise about your specific issue.
