### ISSUE TITLE
Steps are not skipped correctly

### ISSUE THREAD

**Issue by jayesbe** [craue/CraueFormFlowBundle#204]
I have a use case where I have multiple steps (minimum 3). 

Say you have this example. Step 1 should not be skipped. Step 2 will be skipped. 

The flow in this case skips straight to Step 3 because Step 2 is set to get skipped. The flow marks the original Step 1 which should not be skipped.. as to be skipped. This is just wrong.

The following PR fixes this issue. 

https://github.com/craue/CraueFormFlowBundle/pull/203

**Comment by jayesbe** [comment]
new PR https://github.com/craue/CraueFormFlowBundle/pull/243

**Comment by craue** [comment]
It would still be nice to see a test that fails with a flow containing the original `refineCurrentStepNumber` method, also to avoid future regressions. So if you're able to prove that it's either a bug or not, let me know.
