### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pkruithof** [craue/CraueFormFlowBundle#207]
From the todo list in #105 it looks like the 3.0 release is ready to be tagged?

Do you have an indication when we can expect this release? We want to upgrade our project to Symfony 3.0 and unfortunately, this is blocking it.

**Comment by craue** [comment]
I guess it will still take a few days at least. You could use `~3.0@dev` in the meantime if you have to. :smirk:

**Comment by pkruithof** [comment]
Any news on this? The `~3.0@dev` constraint does work, but I prefer to stay on a stable release.

**Comment by craue** [comment]
It's in the making for over two years, so there's no need to rush now.

**Comment by Vizualni** [comment]
@craue any news on stable version 3.0? :+1:

**Comment by akovalyov** [comment]
@craue sorry to bother you, but any updates about it?

**Comment by craue** [comment]
There's no estimated release date yet.

**Comment by dincho** [comment]
This is ridiculous.

**Comment by craue** [comment]
3.0.0 is tagged now.
