### ISSUE TITLE
How to do an edit ?

### ISSUE THREAD

**Issue by jbinfo** [craue/CraueFormFlowBundle#210]
I have an offer entity, I want to generate a unique offer key and save it before to show the form to fill fields to create a new offer.

**Comment by jbinfo** [comment]
@havvg @craue  some help on this issue, thank you.

**Comment by havvg** [comment]
What's issue with this on the aspects of this bundle?

If you want to generate something on the entity, you are free to do, just like you would with a standard Symfony form and pass the pre-created object into the flow.

**Comment by jbinfo** [comment]
@havvg I have generated the offer key and save it to DB, but when I show the first step form to fill some fields it create a new record, this is my code:
```php
$em = $this->getDoctrine()->getManager();

$offer = new Offer();

$flow = $this->get('app.form.flow.offer'); // must match the flow's service id
$flow->bind($offer);
$form = $flow->createForm();

if (!$form->getData()->getOfferingKey()) {
    $em->persist($offer);
    $em->flush();
}

if ($flow->isValid($form)) {
    $flow->saveCurrentStepData($form);
    if ($flow->nextStep()) {
        $form = $flow->createForm();

    } else {
        // flow finished
        $em = $this->getDoctrine()->getManager();
        $em->persist($offer);
        $em->flush();

        $flow->reset(); // remove step data from the session

        return $this->redirect($this->generateUrl('home')); // redirect when done
    }
}
```

**Comment by jbinfo** [comment]
I have resolved this issue, thank you.
