### ISSUE TITLE
current step number is 1 for step 1 and 2

### ISSUE THREAD

**Issue by webdevilopers** [craue/CraueFormFlowBundle#211]
On the very first step of m form I need to check if a $_GET param exists.
If so then the Entity has to be updated. I don't want this to happen when going all the steps back to step 1 - only on initializing the flow.

So far I havn't seen any "onInitialize" method.

So far I used a combination of `getCurrentStepnumber` and `getFirstStepNumber`:
```php
        $venturaConfiguration = new VenturaConfiguration();

        $flow = $this->get('semco.form.flow.ventura_configurator');

        $flow->bind($venturaConfiguration);

        dump($flow);
        echo "F: " . $flow->getFirstStepNumber() . "C: " . $flow->getCurrentStepNumber();
        if ($flow->getCurrentStepNumber() === $flow->getFirstStepNumber()) {
            $partnerId = $request->query->get('partnerId') != '' ? $request->query->get('partnerId') : null;

            $venturaConfiguration->setPartner($partnerId);
        }

        $form = $flow->createForm();
        dump($venturaConfiguration);
```

Though my dumb correctly states that I have a total for **3** steps the current step number on step **1** and step **2** will always show **1**. On step **3** it will then show **2**:
![vc_steps](https://cloud.githubusercontent.com/assets/3479626/12079339/5306f1a4-b235-11e5-9426-65ed3819fe49.png)

Possibly related:
https://github.com/craue/CraueFormFlowBundle/issues/188

**Comment by webdevilopers** [comment]
Do you have the time for a short look @craue ? Just can't imagine what causes this "critical" issue. Thanks in advance.

**Comment by craue** [comment]
What you describe is the expected behavior because prior to calling `$flow->nextStep()`, the current step is the one just submitted.

**Comment by webdevilopers** [comment]
I'm closing this issue for now. But still I think this is related to the issue I described here:
https://github.com/craue/CraueFormFlowBundle/issues/186#issuecomment-168504550

Can you have a look there if there is any relation @craue ?
