### ISSUE TITLE
Fill properties dynamically 

### ISSUE THREAD

**Issue by placid2000** [craue/CraueFormFlowBundle#212]
Hi there

In my example I have two properties: adresses (ArrayCollection) and contactAddress.

On step1 user fills up its contactAddress, then I need this object to be added to the addresses collection and persisted to the session like fromFlow does.

I tryed to achieve this in the symfony form events but without success.

Any idea how I could achieve this? 

I think the problem might be similar to #113.

**Comment by craue** [comment]
How about something like this in the action?

```php
$formData = new UserOrWhatever();
$address = new Address();
$addresses->add($address);
$formData->setAddress($address);
$flow->bind($formData);
```

**Comment by placid2000** [comment]
Hi

Thank you for the proposal..

I ended up solving my issue this way:

public function onPostBindRequest(PostBindFlowEvent $event) {
    $member = $event->getFormData();
    if(!empty($member->getContactAddress())) {
        $member->addAddress($member->getContactAddress());
    }
}

Since the member needs to select the invoiceAddress on the last step
from the Address Collection

Looks like working very well. In this manner I think we can close the issue.

Furthermore I was wondering why you don't pass the current step to the
postBindEvent since it is a known value at this stage and since you pass it
on postBindRequestEvent and postBindSavedDataEvent.
We can get the step number form the flowForm object indeed, but it is just
a matter of consistency.


And by the way.. thanks for the cool bundle:)


2016-01-11 11:59 GMT+01:00 Christian Raue <notifications@github.com>:
