### ISSUE TITLE
Exception "A form can only be submitted once" thrown with xdebug

### ISSUE THREAD

**Issue by placid2000** [craue/CraueFormFlowBundle#214]
Hi again

Surprisingly when I enable debug mode (xdebug) I always get the error message: "A form can only be submitted once" when hitting the $form->handleRequest($request); on line 836 in FormFlow.php.

Furthermore, everything works well when debug mode is disabled.

Any clue?

**Comment by craue** [comment]
What is this debug mode you're talking about? Xdebug is enabled on Travis and all tests pass, so I cannot see an issue with it.

**Comment by placid2000** [comment]
Yes I meant Xdebug enabled. I couldn't figure out where the issue is coming
from yet but I found a workaround by setting a breakpoint right after the
handleRequest method is called.

2016-01-13 22:55 GMT+01:00 Christian Raue <notifications@github.com>:
