### ISSUE TITLE
Suggestion: Clear request data if invalid flow

### ISSUE THREAD

**Issue by Nairebis** [craue/CraueFormFlowBundle#216]
An annoying issue with the current system is that if the user backs up after submitting a form (which does a $flow->reset()), and then resubmits the data, they get an error "This form should not contain extra fields", along with the fields typically showing a "should not be blank" error because the user is submitting data for the last page, and it's currently expecting the first page. This is somewhat ugly.

A simple solution to this is to change this code in FormFlow.php:

		// ensure that the requested step fits the current progress
		if ($requestedStepNumber > $this->getFirstStepNumber()) {
			for ($step = $this->getFirstStepNumber(); $step < $requestedStepNumber; ++$step) {
				if (!$this->isStepDone($step)) {
					$this->reset();
					return;
				}
			}
		}

And insert a line at the reset to this:

				if (!$this->isStepDone($step)) {
					$this->getRequest()->request->replace();
					$this->reset();
					return;
				}

This clears out the posted data and they get a fresh form starting at the first page, without any errors. It also might be appropriate to add this below this case, where there is a call to invalidateStepData().

Another option would be to clear it out and somehow indicate that it's an expired form, but I think at least resetting it to eliminate the error is a good step forward.

If this would have any bad side effects, I'd appreciate an opinion. Thanks!

**Comment by craue** [comment]
What do you mean by "the user backs up after submitting a form"? After finishing the flow, you should just send a redirect.

**Comment by Nairebis** [comment]
It does redirect, but the user can still hit the back button and return to the page. The browser gives a "Confirm Form Resubmit" warning, and if the user resubmits the data, it resubmits with the data of the last flow page. Since FormFlow doesn't have the context anymore after the reset(), it forces the fields for page 1, and thus Symfony gives "This form should not contain extra fields" because the submitted data doesn't match the fields it expects.

**Comment by craue** [comment]
Please take a look at [the redirect after submit feature](https://github.com/craue/CraueFormFlowBundle#enabling-redirect-after-submit). But adding your proposed change would make a test (5bc1dc2d1914067ebda8805596181c5dfd27b9b0) fail by causing a regression to 768572d1784c71887a1cef37dca1d200d55fd707.

**Comment by Nairebis** [comment]
All right, I see that this test fails, so perhaps the change needs to be a bit smarter than that.

What I'm really aiming at here is when trying to submit data to a form that has expired, have it do something friendlier than just give that ugly message. Note this is also a problem if you let a form sit in the browser for a long time, causing the session to expire. Submitting the next page after that also causes that weird error to occur. I'm not sure if the "redirect after submit" would solve that.

I was looking for an easy spot to patch, but I think what really needs to happen is that if a step is submitted and the form key doesn't exist in the session, then it should cancel the submission and give a friendly error that the form has expired, along with the first page and a reset environment. Could something like that be done?

**Comment by Nairebis** [comment]
Hi, I just submitted a pull request with an implementation of the stale form detection that I think is reasonably implemented. When submitted a form, it checks to see if the instance key already exists. If it doesn't, then it gives a friendly error and resets the form.

The only significant change was that it saves an empty form when the instance key is created, but I think that's a minor thing and it helps solves the whole issue of submitting stale forms, or submitting a form with an expired session.

All the tests still run, and I also added a functional test to check submitting to a stale form.

This is actually the first time I've submitted a patch through github, so let me know if I did anything wrong, or if you have any comments on the patch.

**Comment by craue** [comment]
When mentioning a specific PR, you should also refer to it so people can find it. :smirk: It's #220 in this case.

**Comment by Nairebis** [comment]
I thought the "pull request" button was enough, sorry about that!

I'm merging the changes into the current codebase (for some reason, I thought I was using the current), and will look through your comments.

One thing, though: When I ran the tests, I noticed that the latest commit bf0c14e fails one of the tests:

There was 1 failure:

1) Craue\FormFlowBundle\Tests\RevalidatePreviousStepsFlowTest::testRevalidatePreviousSteps_enabled
Failed asserting that '3' matches expected 2.

/home/tim/projects/ycc4/src/vendor/craue/formflow-bundle/Tests/IntegrationTestCase.php:82
/home/tim/projects/ycc4/src/vendor/craue/formflow-bundle/Tests/RevalidatePreviousStepsFlowTest.php:37

FAILURES!
Tests: 236, Assertions: 552, Failures: 1.

If you need any more details, let me know.

**Comment by craue** [comment]
Tests pass when I'm running them locally after rebasing your branch.

**Comment by Nairebis** [comment]
I got that failure when I didn't even have my changes included... bf0c14e was your latest commit (it also happens to fail the same way when I did include my changes). I'm running CentOS 7 with PHP 5.6.17.

**Comment by craue** [comment]
Tests pass on [Travis](https://travis-ci.org/craue/CraueFormFlowBundle/branches), so for me it's hard to find out what could be wrong there.

**Comment by Nairebis** [comment]
I'll do some digging in the next few days and see what's exactly failing.

**Comment by craue** [comment]
I was able to run the tests on CentOS 7 (Build 1511) with PHP 5.4.16 and 5.6.18. They pass as well. Are you sure to have a clean working copy of the repo?

**Comment by Nairebis** [comment]
OK, this is weird. I just tried it again and it worked. I just tried both the bf0c14e branch and my stale-form-detection branch and they both pass.

I have no explanation -- clearly there was something in my environment that caused it, but I can't imagine what it would be. I am very certain I had a clean copy because I specifically made sure I was running the bf0c14e commit, and it failed the same way my own branch failed. And it was just that one test, which looking at it, looks pretty straightforward. Damn it, I should've dumped the DOM from the crawler object for that test. That might've told the story.

Well, I'll keep poking around and see if I can reproduce it.

**Comment by craue** [comment]
Maybe just a caching issue. Better spend your time working on #220. :smirk:

I wonder why you're focused on that specific commit. So make sure to rebase your branch on master.

**Comment by Nairebis** [comment]
Maybe the cache... still weird that it only produced that one fail. Oh well.

That commit was from 2/23, which was the latest when I last did a pull.

**Comment by Nairebis** [comment]
I hit a snag that I'm hoping you have a quick answer for... I changed the message to use the translation stuff by adding an Event/FormExpiredEvent.php and EventListener/FormExpiredEventListener.php, and added a message called "craueFormFlow.formExpired" in validators.en.yml.

When I try it in my real application, it's just showing "crauseFormFlow.formExpired" for the error, but when I run the FormFlow tests, it's pulling the correct message. I've tried clearing the cache. Any insight?

**Comment by craue** [comment]
This indeed sounds like a caching issue. I stumbled upon that when `PreviousStepInvalidEvent` was added. :laughing:

I'd better call it `FlowExpiredEvent` than `FormExpiredEvent`.

**Comment by Nairebis** [comment]
Okay, all your suggestions are incorporated, except the ones I commented on. Would I normally do another pull request? Not sure, so here's just the link to the commit:

https://github.com/craue/CraueFormFlowBundle/commit/e8c38bc728a8d47d56c1984f37a34f00b8953ac2

Let me know if anything else needs to be changed.

**Comment by Nairebis** [comment]
See what you think of this:

https://github.com/Nairebis/CraueFormFlowBundle/commit/dabc473ba9c1bd5a74461327b5a2e3f0229a056f

**Comment by Nairebis** [comment]
OK, changes + squashed commit:

https://github.com/Nairebis/CraueFormFlowBundle/commit/519b9534b96acf7b2ef583a94793adfe6c3601b7

**Comment by craue** [comment]
Implemented in #220.
