### ISSUE TITLE
Clickable steps in list template (isStepLinkable not working?)

### ISSUE THREAD

**Issue by rvmourik** [craue/CraueFormFlowBundle#227]
Hi There,

I'm very excited about the bundle, but i do have a question. According to the isStepLinkable twig method it seems possible to make previous steps linkable in de steps template.

However, it's not working for me. Does this need any further configurering on my end, or should it work out of the box?

I'm using a form flow with a single form type.

Regards.

Robbert

**Comment by craue** [comment]
It only works when [dynamic step navigation](https://github.com/craue/CraueFormFlowBundle#enabling-dynamic-step-navigation) is enabled.

**Comment by rvmourik** [comment]
Thanks Christian, it works!
