### ISSUE TITLE
Flow changing behaviour with XDebug session on

### ISSUE THREAD

**Issue by ujhgj** [craue/CraueFormFlowBundle#230]
Hello,

Do you have any clue, why I face such behaviour? 
I mean, flow acts unexpectedly. For example, messing steps or finishing untimely.

I'm using Symfony3 and dev-master of this bundle.

**Comment by craue** [comment]
Another Xdebug-related issue was reported in #214. But Xdebug is enabled on Travis and all tests pass, so I cannot see what could be wrong there.
