### ISSUE TITLE
Step::getLabel

### ISSUE THREAD

**Issue by fracsi** [craue/CraueFormFlowBundle#236]
I tried to name one of my steps as Date, but it is a PHP callable so `Step::getLabel` tries to execute it.
Maybe it should be marked explicitly if a label is a callable and not only by checking in the getLabel call by  `is_callable($this->label)`

A simple case to reproduce:
```
protected loadStepConfig() {
    return [
        [
            'label' => 'date',
            'form_type' => \Symfony\Component\Form\Extension\Core\Type\FormType::class
    ];
}
```

**Comment by craue** [comment]
Thank you for reporting this issue, @fracsi.

As #237 doesn't seem to be the right approach. How about adding a new class `StepLabel` which would be explicit about the label being callable or not. I'll prepare a PR to see how it pans out.

**Comment by fracsi** [comment]
@craue For maintainability i think the new class would be the best option.
