### ISSUE TITLE
Could not parse property path "[]" while using collection prototype

### ISSUE THREAD

**Issue by andrzejdziekonski** [craue/CraueFormFlowBundle#239]
Hi, 
i faced the problem when using scenario described below at Symfony 3.0: 

- my form data entity is Profile
- it contains few translatable fields (powered by https://github.com/KnpLabs/DoctrineBehaviors#translatable)
- in my first step form i would like to use some fields that are translated for current locale, so i did: 
```
$builder->add('translations', CollectionType::class, array(
                'entry_type' => ProfileTranslationType::class,
                'allow_add'    => true,
                'label' => false,
                'by_reference' => false
            ))
```
which is: 
```
class ProfileTranslationType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        $guessedLocale = strtoupper(substr(\Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE']),0,2));
        $builder
            ->add('shortBio', TextareaType::class, array(
                'required' => false,
                'label' => false,
                'attr' => array('placeholder' => 'Type couple words about yourself'),
                'mapped' => false
            ))
            ->add('interests', TextareaType::class, array(
                'required' => false,
                'label' => false,
                'attr' => array('placeholder' => 'Interest'),
                'mapped' => false
            ))
            ->add('locale', HiddenType::class, array('data' => $guessedLocale));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ProfileTranslation',
        ));
    }

    public function getBlockPrefix()
    {
        return 'profile_translation';
    }
    
}
```
and then in twig: 
`{{ form_widget(form.translations.vars.prototype.shortBio) }}`

i can pass the step with prototype fields but when i try to go back fatal error comes: 
**Could not parse property path "[]". Unexpected token "[" at position 0**

Any tips how could i resolve this issue? Or maybe there is better way of managing KNP translatable in forms at Symfony 2.8+? (i saw https://github.com/a2lix/TranslationFormBundle is not stable for current Symfony versions)

**Comment by craue** [comment]
Can you find out if it's really an issue with this bundle? And if so, could you set up a failing test?

**Comment by elyotechgit** [comment]
Hi @andrzejdziekonski, 
Did you a find a solution for this issue ?
I'm facing the exact same thing.

Thanks
