### ISSUE TITLE
Passing options to buildForm

### ISSUE THREAD

**Issue by ValBrunhes** [craue/CraueFormFlowBundle#240]
Hi,
I'm a beginner with symfony and I'm trying to pass a value from my controller to my buildForm like this:
[http://stackoverflow.com/questions/29811837/symfony2-passing-options-to-buildform](url)
but it doesn't work.
Any tips how could i resolve this issue?

**Comment by ValBrunhes** [comment]
`$formData = new CreateVisite();
        $flow = $this->get('spanc.form.flow.visite');
        $flow->bind($formData);
        $form = $flow->createForm(VisiteType::class, $formData, ['id' => $id]);`

Sorry here is my code

**Comment by ValBrunhes** [comment]
`$formData = new CreateVisite();
        $flow = $this->get('spanc.form.flow.visite');
        $flow->bind($formData);
        $form = $flow->createForm(VisiteType::class, $formData, ['id' => $id]);`

Sorry here is my code

**Comment by craue** [comment]
For 2.1, `createForm` has only one argument `$options`. For upcoming 3.0, see https://github.com/craue/CraueFormFlowBundle#passing-generic-options-to-the-form-type.

**Comment by andrzejdziekonski** [comment]
If i use method: 
`$flow->setGenericFormOptions(array('action' => 'targetUrl'));`

how can i fetch the parameter inside step forms or inside the flow (so i can pass it to form types via form_options)?

**Comment by craue** [comment]
@andrzejdziekonski, these options will be passed to the form type of each step. You don't need to pass them manually.

**Comment by andrzejdziekonski** [comment]
I see. What about third party parameters? Let's say i need to pass some parameter (i.e. 'locale') for my first step form field to filter collection with this param. With setGenericFormOptions method i get error that option '...' does not exist. What is the best way to achieve that?

**Comment by craue** [comment]
@andrzejdziekonski, see https://github.com/craue/CraueFormFlowBundle#passing-step-based-options-to-the-form-type.

**Comment by andrzejdziekonski** [comment]
I know i can pass parameters to form via form_options but question is how to pass dynamic ('locale' param is depending on user geo) parameter from controller to flow since i create an instance from service?

**Comment by craue** [comment]
@andrzejdziekonski, then you'd need to override `getFormOptions` as shown in the section mentioned previously.
