### ISSUE TITLE
How to render each form row separately?

### ISSUE THREAD

**Issue by clytemnestra** [craue/CraueFormFlowBundle#241]
I've created a form consisting of multiple steps.

To render each row at each step separately, do I need to check the curent step like so?

```twig
    {% if flow.getCurrentStepNumber() == 1 %}
        <div>
            {{ form_row(form.numberOfWheels) }}
        </div>
    {% endif %}
```

because I want to do something like
```twig
 {{ form_row(form.numberOfWheels, {'attr': {'class': 'testclass'}}) }}
```
for each row, but I can't do it without checking the curent step because it will throw an error.

Is there another way? How to render each row? I'm thinking there has to be a way to have a different view or partial for each step, but the docs don't seem to cover that.

**Comment by craue** [comment]
Form rendering is completely up to you. There's nothing bundle-specific.

**Comment by clytemnestra** [comment]
I know, but I can't do this, when the two are from different steps:

```php
                        {{ form_widget(form.jobName,{'attr':{'placeholder':'Enter name of request'}}) }}          
                        {{ form_widget(form.quantity,{'attr':{'placeholder':'Enter quantity'}}) }}
```

because I get this

```php
Method "quantity" for object "Symfony\Component\Form\FormView" does not exist in @App\Pages\getAQuotation.html.twig at line 46```

I need to do this

```php

                    {% if flow.getCurrentStepNumber() == 1 %}
                        {{ form_widget(form.jobName,{'attr':{'placeholder':'Enter name of request'}}) }}
                    {% endif %}
                    {% if flow.getCurrentStepNumber() == 2 %}
                        {{ form_widget(form.quantity,{'attr':{'placeholder':'Enter quantity'}}) }}
                    {% endif %}
```

check if it's the current step and render the field(s) of that step only. This becomes very hard when you have a lot of steps. Is there a way to not check the curent step?

**Comment by craue** [comment]
At some point, you would need to check either the step number or if the fields you're trying to render actually exist. The former could also be done in the controller to decide which template to render, so you could add partials for your needs. But as I already said, the bundle itself doesn't provide (or enforce) such mechanism.

**Comment by clytemnestra** [comment]
Alright, I'm still using it by checking each step. It's slightly annoying but at least it gets the job done.
