### ISSUE TITLE
Multiple forms → flow is expired

### ISSUE THREAD

**Issue by ntoniazzi** [craue/CraueFormFlowBundle#249]
Hi,
I have 2 forms on a page, one of them is built by a flow. When I post from the second one, the flow form raises the error "flow is expired", even though it was not submitted.
When creating the form, there is a test that checks whether the HTTP method is either POST or PUT. It should also check that this form has been submitted.

**Comment by craue** [comment]
@Nairebis, do you see how this could be fixed? `Craue\FormFlowBundle\Tests\CreateVehicleFlowTest::testCreateVehicle_flowExpired` fails when I try to apply this change:

```patch
diff --git Form/FormFlow.php Form/FormFlow.php
--- Form/FormFlow.php
+++ Form/FormFlow.php
@@ -633,7 +633,7 @@
 			$reset = true;
 		}
 
-		if (in_array($this->getRequest()->getMethod(), array('POST', 'PUT')) && !$this->dataManager->exists($this)) {
+		if (in_array($this->getRequest()->getMethod(), array('POST', 'PUT')) && $this->getRequest()->request->get($this->getName()) !== null && !$this->dataManager->exists($this)) {
 			// flow is expired, drop posted data and reset
 			$this->getRequest()->request->replace();
 			$reset = true;
```

I wonder if there's something wrong with that test or if the issue could/should be solved differently.

**Comment by craue** [comment]
Thank you for reporting this issue, @ntoniazzi. It's fixed now.
