### ISSUE TITLE
Completed vs awaiting steps

### ISSUE THREAD

**Issue by kshishkin** [craue/CraueFormFlowBundle#260]
Is this something you'd consider adding to the codebase? If so, do you want me to push it? And to which branch?

I'm adding progress bar to my flow. 
It consists of 3 bars:
1. Static-length bar showing percentage completed
2. Dynamic length bar getting longer with each step - contains navigable step labels
3. Dynamic length bar getting shorter with each step - contains step labels to be performed

I've extended FormFlow as these methods turned out to be handy.

``` php
/**
 * List steps for which there's data provided
 * 
 * @return array - performed steps
 */
public function getPerformedSteps()
{
    $steps = $this->getSteps();
    $stepData = $this->retrieveStepData();
    $performedSteps = array();

    foreach ($steps as $step)
    {
        $stepNumber = $step->getNumber();
        if ($this->isStepDone($stepNumber))
            $performedSteps[] = $step;
    }

    return $performedSteps;
}

/**
 * List steps for which no data is provided yet
 * 
 * @return array - awaiting steps
 */
public function getAwaitingSteps()
{
    $steps = $this->getSteps();
    $stepData = $this->retrieveStepData();
    $awaitingSteps = array();

    foreach ($steps as $step)
    {
        $stepNumber = $step->getNumber();
        if (!$this->isStepDone($stepNumber))
            $awaitingSteps[] = $step;
    }

    return $awaitingSteps;
}

/**
 * Count steps for which there's data provided
 * 
 * @return int - count of performed steps
 */
public function getPerformedStepsCount()
{
    $performedSteps = $this->getPerformedSteps();

    return count($performedSteps);
}

/**
 * Count steps for which no data is provided yet
 * 
 * @return int - count of awaiting steps
 */
public function getAwaitingStepsCount()
{
    $awaitingSteps = $this->getAwaitingSteps();

    return count($awaitingSteps);
}
```

**Comment by craue** [comment]
Although I don't like the `Flow` class becoming even more bloated, I'm fine right now with adding such methods. But we have to be careful naming them. How about "remaining steps" instead of "awaiting steps"? I don't have a fitting word for the steps being "done" as that means they are either submitted or skipped, maybe just keep it like that and call them "steps done". Thus the methods could be named "getStepsRemaining" and "getStepsDone". What do you think?

**Comment by kshishkin** [comment]
All understood. I'll rename the methods & request pull.

**Comment by craue** [comment]
Alright. Target should be the master branch.
