### ISSUE TITLE
Percentage of completion

### ISSUE THREAD

**Issue by kshishkin** [craue/CraueFormFlowBundle#261]
Shell this be something desired in the bundle, please let me know.

I've extended the bundle to retrieve percentage of completion.
By default it weights all steps equally, but you can configure by custom step parameter (see #260).

Forgotten settings are auto-filled in proportionally & the numbers scaled in case "furious development" lead someone to configure for percentages that don't sum up to 100.

**Comment by craue** [comment]
Could you elaborate on this? I'm afraid I don't understand what it's about.

**Comment by kshishkin** [comment]
I'm not sure on this, as you don't want the FormFlow to bloat & what I have in mind may be too large. 
To put things simple:
```php
//FormFlowInterface.php
public function getPercentageCompleted();
```

The actual implementation may be very simplistic like 100*stepsCompletedCount/stepsCount. I tried that & for me it turned out insufficient. I wanted to say that e.g. Step1 accounts for 10%, Step2 60% & Step3 30%. That's where #263 came in handy to me.

What are your thoughts?

**Comment by craue** [comment]
Right now, I'd say this is indeed a rather custom feature that should go into your `FormFlow`-extending class.
