### ISSUE TITLE
How to inject Entity Manager in form classes?

### ISSUE THREAD

**Issue by ignatiusreilly2** [craue/CraueFormFlowBundle#264]
I need to have form classes having access to the Entity Manager (or alternatively to Symfony3 services).
The use case for this is to build dynamic drop-down lists based on database lookups.

The formflow service can be injected a @doctrine.orm.entity_manager argument, but it doesn't help, as I don't see how this can be in turn injected into the form classes of the flow.

**Comment by craue** [comment]
Define your form type as a service, see [here](https://github.com/craue/CraueFormFlowDemoBundle/blob/8ea789828b74af2c1ade402dd89edc26e8b57d34/Resources/config/form_type.xml#L23) and [here](https://github.com/craue/CraueFormFlowDemoBundle/blob/8ea789828b74af2c1ade402dd89edc26e8b57d34/Form/Type/LocationRegionType.php#L23).
