### ISSUE TITLE
Flow only keeps final step data with form name / blockPrefix set to null or an empty string

### ISSUE THREAD

**Issue by webdevilopers** [craue/CraueFormFlowBundle#270]
I'm still using *2.1.8*. I had to refactor a lot of forms, some of them were flows.
I had to override the `getName` aka as `getBlockPrefix` with Symfony > *2.8* and made them return `null` or `''`. This way the generated array notation would disappear:

```html
name="engine" <!-- instead of `[createVehicle][engine]`
```

Everything seemed to work fine until I submitted the final step. All data was gone from the `data_class` except the final one I entered.

I re-added a name / prefix so far.

Any idea if this will still be a problem with #105 after #215?

Maybe I will be able to check it out next year anyway. Just asking the `master` for now!? ;)

**Comment by craue** [comment]
Why do you return `null` or `''` at all? Is this even allowed/supported by Symfony?

**Comment by webdevilopers** [comment]
Actually it seems like a legit way:
* http://stackoverflow.com/questions/8416783/symfony2-form-component-creating-fields-without-the-forms-name-in-the-name-att
* http://stackoverflow.com/questions/13384056/symfony2-1-using-form-with-method-get/13474522#13474522

A common use case are GET forms for filtering to prevent the query string getting to long.

Though SETTING the `blockPrefix` works fine I wanted to let you know that there is an issue with the  other configuration.

**Comment by craue** [comment]
Although it's not forbidden to use an empty name for a form, it's a bad idea and obivously won't work for flows. I don't see a need to fix/workaround that.
