### ISSUE TITLE
use of data transfer objects instead of doctrine entities 

### ISSUE THREAD

**Issue by kermorgant** [craue/CraueFormFlowBundle#272]
Hello,

Because of complex validation rules (involving translations & collections), I'm trying to see how "data transfer objects" ([after reading this blog entry](https://stovepipe.systems/post/rethinking-form-development)) could help me better manage what's happening during validation and persist operations.

But the case I'm working on involves a flow, so I wonder how well that concept would work and what change I'd have to make. I've already managed to hydrate my data transfer objects, but for the persist operation.

For the save operation, I guess I have to replace 	        
`
$flow->saveCurrentStepData($form);
`

by a persist operation based on my new classes instead.

Do you see anything wrong with that ?

Regards

**Comment by craue** [comment]
For forms (and thus flows) you can use any object, not necessarily entities, so I don't see any issues here.

**Comment by kermorgant** [comment]
Indeed, I worked it out with DTOs.
