### ISSUE TITLE
use collectionType vichupload

### ISSUE THREAD

**Issue by imsheng** [craue/CraueFormFlowBundle#274]
![20170212195706](https://cloud.githubusercontent.com/assets/10435075/22862040/cc70ee7a-f161-11e6-85bf-0fcc9e15673f.png)
![qq 20170212195122](https://cloud.githubusercontent.com/assets/10435075/22862041/cc738388-f161-11e6-8aaf-ef591910bc2e.png)

![qq 20170212222256](https://cloud.githubusercontent.com/assets/10435075/22862870/02c35cb4-f172-11e6-9bc7-ce090be48772.png)
![qq 20170212222349](https://cloud.githubusercontent.com/assets/10435075/22862871/02e6e0bc-f172-11e6-92a7-dfc33fa920cd.png)

**Comment by craue** [comment]
What exactly are you trying to tell me? As #151 points out, VichUploaderBundle doesn't seem to work well with the flow's upload handling.

**Comment by imsheng** [comment]
sorry, i dont't speak english
array_merge_recursive cannot merge data perfectly
![02e6e0bc-f172-11e6-92a7-dfc33fa920cd](https://cloud.githubusercontent.com/assets/10435075/22867553/926d0cae-f1c5-11e6-891d-ef9fd7ec2d8b.png)

**Comment by craue** [comment]
Can you try disabling VichUploaderBundle to see if it's causing this issue?

**Comment by imsheng** [comment]
I don't think uploaderbundle has anything to do with it ,  the file is separate treatment and then merge.

**Comment by craue** [comment]
Would you create a failing test or at least a demo app showcasing the issue?

**Comment by BlazingSun** [comment]
Does this fix it? https://github.com/craue/CraueFormFlowBundle/pull/276

**Comment by craue** [comment]
This should be fixed by #389.
