### ISSUE TITLE
Using the "Symfony\Bridge\Twig\Extension\FormExtension::$renderer" property is deprecated

### ISSUE THREAD

**Issue by jbennegent** [craue/CraueFormFlowBundle#284]
Hello,

Just upgraded from Symfony 3.1 to 3.2.

Some tests in PHPUnit show deprecation notices 

`Using the "Symfony\Bridge\Twig\Extension\FormExtension::$renderer" property is deprecated since version 3.2 as it will be removed in 4.0`

I realize that :

- the forms that use CraueFormFlowBundle show this deprecation notice
- the forms that don't use CraueFormFlowBundle don't show this deprecation notice
- I don't use the $renderer property or something similar in my own code

So I'm wondering is this could come from the CraueFormFlowBundle

Any idea about this ?

Thanks !

**Comment by craue** [comment]
[Running the tests](https://travis-ci.org/craue/CraueFormFlowBundle/jobs/213772878#L281) (with 3.2.6) doesn't trigger any deprecation notices and there's no occurrence of `renderer` in the code. I guess you'll have to find out where else it's coming from. 😏

**Comment by jbennegent** [comment]
OK thanks 
Guess I have to look closer :smirk:
