### ISSUE TITLE
Change button order and add icons

### ISSUE THREAD

**Issue by Robouste** [craue/CraueFormFlowBundle#285]
Hi, 

I would like to know if we can change button order ? The next button is before the previous button, which is not intuitive. 

Plus, I would like to add font icons inside the button but when I do : 
`craue_formflow_button_label_back: '<i class="material-icons left">navigate_before</i>Previous'`

I get the raw html inside de button.

I'm doing this as a workaround but it's not clean : 
```js
    var icons = {
        prev : '<i class="material-icons left">navigate_before</i>',
        next : '<i class="material-icons left">navigate_next</i>',
        reset : '<i class="material-icons left">refresh</i>',
        finish : '<i class="material-icons left">save</i>'
    };

    $(".step-next").prepend(icons.next);
    $(".step-prev").prepend(icons.prev);
    $(".step-reset").prepend(icons.reset);
    $(".step-finish").prepend(icons.finish);
```

**Comment by craue** [comment]
It's always possible to just override the template to make it fit your special needs. :smirk:

**Comment by Robouste** [comment]
Yep, I'll give it a try but I'm new to all the symfony stuff.

If I may give my opinion, "next" button should be after "previous" :)

**Comment by craue** [comment]
Take a look at [the docs](https://github.com/craue/CraueFormFlowBundle#create-a-form-template). There's a note about CSS for the correct button order.

**Comment by Robouste** [comment]
Applying a class with `float:left;` to the `previous `button did the trick, thanks :)
