### ISSUE TITLE
State of 3.0?

### ISSUE THREAD

**Issue by temp** [craue/CraueFormFlowBundle#294]
Hi,

I am in the middle of the migration of our app to Symfony 3.3, and have just stumbled over several issues, which seem to be fixed in form flow bundle 3.0. But a final release was never released.

Are there known problems? Anything else that would prevent a 3.0 release?

**Comment by craue** [comment]
3.0.0 is tagged now.

**Comment by temp** [comment]
Awesome, thanks!
