### ISSUE TITLE
GroupSequence not working With Craue

### ISSUE THREAD

**Issue by jmwierzbicki** [craue/CraueFormFlowBundle#300]
```
                'form_options' => [
                    'validation_groups' => new GroupSequence(['Step1', 'ApiCheckStep1']), 
                ],
```
Short story. I need to validate field, and then access external API to check if this value is not already taken.
If i set GroupSequence in Data object it works, but it sequentially validates given groups on every step and this means that on step 2>3 i have to wait for validation from step1.

My code sample throws:
> Warning: Illegal offset type in isset or empty

Is there any workaround?

**Comment by craue** [comment]
Good catch! I just tagged 3.0.1 which supports using a GroupSequence.
