### ISSUE TITLE
Edit step form, links not clickable ?

### ISSUE THREAD

**Issue by Dranac** [craue/CraueFormFlowBundle#304]
Hello ! 

I have a little problem about steps. I'm not sure if i missed a doc. somewhere or if it's not implemented.

I have a form with 3 step. 
I can edit/create an entity with it (everything is ok about the flow). 

Problem is that when i access the edit form, i can't navigate through the different step of my form. I have to click the `next` button to make navigation clickable.

Do you think there's a way to make step links clickable when entity of the form is in `edit` mode ?

**Comment by craue** [comment]
Maybe #56 helps.

**Comment by Dranac** [comment]
Yes it is ! Thanks a lot.
