### ISSUE TITLE
Save current step to a database

### ISSUE THREAD

**Issue by kironet** [craue/CraueFormFlowBundle#309]
Hi,

Is it possible to save current step to a database?
Example what I mean:

I have checkout form
Step 1:
Billing and Shipping address + email and telephone
Step 2:
Shipping method
Step 3:
Payment method

So I need to save Step 1 to the database after clicking "next".
I want to have customer's email so I can send him an email if he leaves checking out process.

Hope this make sense.

Thanks

**Comment by MichaelNeyl** [comment]
Hello Kironet,

Did you find a solution for this issue ?

Thank's for your feedback :)
