### ISSUE TITLE
Symfony4: createForm expect a string not a Type.

### ISSUE THREAD

**Issue by brunonic** [craue/CraueFormFlowBundle#319]
in FormFlow.php 

    // createFormForStep

    return $this->formFactory->create($formType, $this->formData, $options);

`$formType` must be a string.

Then when I do something like 

    $form = $exempleFlow->createForm();

I got this 

    Expected argument of type "string", "App\Form\ExempleType" given

**Comment by craue** [comment]
See https://github.com/craue/CraueFormFlowBundle/pull/320#issuecomment-552805996.
