### ISSUE TITLE
error in second step due to entity

### ISSUE THREAD

**Issue by mdimitris** [craue/CraueFormFlowBundle#323]
Hello! I try to combine two different forms (approach b) but when I go to second step I get an error saying 

> Neither the property "finalGrade" nor one of the methods "getFinalGrade()", "finalGrade()", "isFinalGrade()", "hasFinalGrade()", "__get()" exist and have public access in class "App\Entity\Application".

I am certain it has to do with enitities but I cant figure out what I have to change..
Thanks in advance

**Comment by craue** [comment]
It's impossible to tell what's wrong from this brief description.

**Comment by mdimitris** [comment]
ok I found the issue..My entity didnt include the other entity.,,
