### ISSUE TITLE
The "craue.form.flow.hidden_field_extension" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0.

### ISSUE THREAD

**Issue by seyfer** [craue/CraueFormFlowBundle#338]
> [2019-06-13 17:32:30] php.INFO: User Deprecated: The "craue.form.flow.hidden_field_extension" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"craue.form.flow.hidden_field_extension\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at vendor/symfony/dependency-injection/Container.php:282)

could this issue be fixed, please?
seen in Symfony v3.4

**Comment by craue** [comment]
Since there's no deprecation triggered by running the tests, it would be good to know under which conditions this happens. Are you accessing this service in your own code?
