### ISSUE TITLE
Error in PreviousStepInvalidEventListener

### ISSUE THREAD

**Issue by pdias** [craue/CraueFormFlowBundle#347]
I'm using SF3.4 and from last update in master i have this error:

`Type error: Argument 1 passed to Craue\FormFlowBundle\EventListener\PreviousStepInvalidEventListener::setTranslator() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Symfony\Component\Translation\DataCollectorTranslator given`

Thanks.

**Comment by craue** [comment]
Is `symfony/translation-contracts` installed?

**Comment by pdias** [comment]
Yes, is installed.

**Comment by craue** [comment]
Thank you for reporting this issue. Should be fixed now.
