### ISSUE TITLE
Skip step when going back

### ISSUE THREAD

**Issue by pelkas** [craue/CraueFormFlowBundle#356]
Is it possible to skip steps on back? For example return to step 3 from step 5 skipping step 4?

**Comment by craue** [comment]
Yes. Skipping steps works in both directions.

**Comment by pelkas** [comment]
Sorry I did not explain exactly. I want to skip step only when I going back. For now skipping work for both directions for me

**Comment by pelkas** [comment]
Ok, I achieve this using requested transition

`
'skip' => function($stepNumber, FormFlowInterface $flow) {
return $flow->getRequestedTransition() == 'back';
},
`
