### ISSUE TITLE
FormFlowEvent.php breaks opcache preloading functionality

### ISSUE THREAD

**Issue by megawilddaddy** [craue/CraueFormFlowBundle#363]
https://github.com/craue/CraueFormFlowBundle/blob/master/Event/FormFlowEvent.php

```
Sep 07 10:31:15 asus php-fpm7.4[25330]: [07-Sep-2020 10:31:15] NOTICE: PHP message: PHP Fatal error:  Cannot declare class Craue\FormFlowBundle\Event\FormFlowEvent, because the name is already in use in /home/vasily/Projects/fxbo.local/vendor/craue/formflow-bundle/Event/FormFlowEvent.php on line 26
```

**Comment by craue** [comment]
@megawilddaddy @piotrantosik Is there a way to test this (or rather trigger this error) on Travis?

**Comment by piotrantosik** [comment]
I think this is not possible or hard to reproduce. I have seen an error when I play with preloading on production Symfony app.
PHP docs about preloading - https://www.php.net/manual/en/opcache.preloading.php

**Comment by craue** [comment]
Problem is I cannot use it locally and would like to avoid future regressions (e.g. when being tempted to create similar workarounds for other classes). 😏
