### ISSUE TITLE
Reset steps when something changed in previous step

### ISSUE THREAD

**Issue by pelkas** [craue/CraueFormFlowBundle#364]
Hello, I have a 7 step form. I need to reset all next steps if user go back and change something. For example:
user go to step 6, then back to step 2 and change one field so I need to reset all steps after step 2 and recreate them again.

**Comment by craue** [comment]
Use a [PostBindFlowEvent](https://github.com/craue/CraueFormFlowBundle#using-events) to call `$this->invalidateStepData($this->getCurrentStepNumber() + 1)`.
