### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by tjveldhuizen** [craue/CraueFormFlowBundle#373]
Is there any plan to make this project compatible with PHP 8? Is it correct, that adding it to the Travis configuration should be a good first step?

**Comment by craue** [comment]
[I'm on it.](https://travis-ci.org/github/craue/CraueFormFlowBundle/builds/746554335) Give it some more time. 😏

**Comment by craue** [comment]
Ah I forgot, version 3.4.0 is out. 😄
