### ISSUE TITLE
Save on current step button

### ISSUE THREAD

**Issue by mcgoode** [craue/CraueFormFlowBundle#376]
Any advice on how to have a button that saves everything in the form to the DB?

I know I could probably do a flush on next, but want I wanted a separate button for `save and quit`?

**Comment by craue** [comment]
You could use [DoctrineStorage](217) instead of the (default) SessionStorage.

**Comment by mcgoode** [comment]
I opted to just persist the redirect. 


I added an HiddenType input to the step(s) i wanted to have the save and quit functionallity.
```


On the form I added a button to attach a JS event to:
```
<button type="button" data-intro="To save your progress and come back later" class=" submit-flow btn btn-success save_and_quit float-right ml-2">Save and quit</button>
```

**Comment by mcgoode** [comment]
Sorry for the open an close not sure what happen.
