### ISSUE TITLE
Use CraueFormFlowBundle for 2 non related entities/model

### ISSUE THREAD

**Issue by chrisVdd** [craue/CraueFormFlowBundle#381]
Before "jumping" into the code, I was wondering..

Can I use CraueFormFlowBundle with:

- a  form data class at the step 1
- an entity at the step 2

**For the context:**
- step1 : form for questions to the user
- step2 : depending the answer gave to step1, update the entity User or the entity Post

I saw the example of the demo here https://github.com/craue/CraueFormFlowDemoBundle/blob/3.4.x/Form/CreateVehicleFlow.php but it's 2 related entities.

Thanks for your answers

**Comment by craue** [comment]
see #28
