### ISSUE TITLE
Step list structure

### ISSUE THREAD

**Issue by delhombre** [craue/CraueFormFlowBundle#396]
How to override the structure of the step list ? I tried to extends the template in bundles/CraueFormFlowBundle/FormFlow.... like described in the doc but it seems not working. I have this error message "Template "@CraueFormFlow/FormFlow/stepList_blocks.html.twig" cannot be used as a trait."

**Comment by craue** [comment]
What exactly did you try? Some details would be helpful.

**Comment by delhombre** [comment]
I'm trying to override the steplist html structure and the default classes.

**Comment by craue** [comment]
With a file `templates/bundles/CraueFormFlowBundle/FormFlow/stepList_customization.html.twig` in your project?

**Comment by delhombre** [comment]
![code](https://user-images.githubusercontent.com/52165447/150777882-ef930bff-b80a-4f82-b316-f7b078204ccb.png)
 How to override this block. Thanks

**Comment by craue** [comment]
Put it in `templates/bundles/CraueFormFlowBundle/FormFlow/stepList_customization.html.twig`, prepend `{% use '@CraueFormFlow/FormFlow/stepList_blocks.html.twig' %}` and customize everything the way you want.

**Comment by delhombre** [comment]
![code](https://user-images.githubusercontent.com/52165447/150787188-7c20d88f-cd57-4442-9e67-c96cbbe94e68.png)
 RuntimeError: Variable "loop" does not exist.

**Comment by craue** [comment]
Don't copy the contents of `stepList_blocks.html.twig` into this file but override it separately.

**Comment by delhombre** [comment]
It works. Thank you.

**Comment by craue** [comment]
You're welcome.
