### ISSUE TITLE
Lost data for a 3-steps flow when pressing back button twice then next button

### ISSUE THREAD

**Issue by fdiedler** [craue/CraueFormFlowBundle#397]
Hi,

I think there is a bug in the flow. I have 3 steps and the buf appears if :
- Fill the 1st and 2nd steps (we are on the last step)
- Press back button twice (we are on the first step)
- Press next button once (we are on the second step) -> the submitted data are lost

NB: If I use the _allowDynamicStepNavigation_ option, it works fine.

Does I need to configure something ? 

Thanks,

**Comment by fdiedler** [comment]
@craue I understand the issue if previous step influences the current step. It is not an issue in my flow so maybe put an option to avoid data loss ? (I prefer not using _allowDynamicStepNavigation_)
For user experience, it would be better ;)
Thanks,

**Comment by craue** [comment]
Well, I guess `allowDynamicStepNavigation` is this option. What's the reason you don't want to use it?

**Comment by fdiedler** [comment]
@craue Indeed, I found a way to remove links in steps because I don't want to allow users to "jump" over steps.
That is why initially I didn't want to use this option.
But now, it is okay.
Thanks,
