### ISSUE TITLE
Handle file uploads with Amazon Web service S3

### ISSUE THREAD

**Issue by fdiedler** [craue/CraueFormFlowBundle#398]
Hi,

I use AWS S3 for storing files.
How set the property `$handleFileUploadsTempDir = '/path/for/flow/uploads';` in this case ?

I saw a PR for using Gaufrette abtraction layer but I am not sure it will be merged soon :(

Thanks,

**Comment by craue** [comment]
That's not possible currently.
Since you already spotted #353, feel free to work on (help) implementing such feature. 😏

**Comment by fdiedler** [comment]
@craue Unfortunally, I don't have the level to help on this.
Hope a nice people would do it because I think it is a great feature that fits with this great bundle :)
Thanks,
