### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by Soimil** [craue/CraueFormFlowBundle#423]
When trying to install it in a Symfony 7 project, I received the following message:
 
Problem 1
    - Root composer.json requires craue/formflow-bundle ^3.6 -> satisfiable by craue/formflow-bundle[3.6.0].
    - craue/formflow-bundle 3.6.0 requires symfony/config ~4.4|~5.3|^6.0 -> found symfony/config[v4.4.0, ..., v4.4.44, v5.3.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but these were not loaded, likely because it conflicts with another require.

**Comment by justicesandram** [comment]
> When trying to install it in a Symfony 7 project, I received the following message:
> 
> Problem 1 - Root composer.json requires craue/formflow-bundle ^3.6 -> satisfiable by craue/formflow-bundle[3.6.0]. - craue/formflow-bundle 3.6.0 requires symfony/config ~4.4|~5.3|^6.0 -> found symfony/config[v4.4.0, ..., v4.4.44, v5.3.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but these were not loaded, likely because it conflicts with another require.

Have the same problem
