### ISSUE TITLE
How to get an field not mapped?

### ISSUE THREAD

**Issue by xthiago** [craue/CraueFormFlowBundle#44]
Hi,

In my form I have an choice field not mapped to entity ('mapped' => false). The method FormFlow::getFormOptions() receives $formData, but that only contains data of entity. How to get value of these field not mapped?

**Comment by progzy** [comment]
@craue : is using a DTO still the way to deal with unmapped fields please? (ie image upload)

**Comment by anygroup36** [comment]
@crauze i think using non-mapped field is verry common. There is no way to get this data....
1 step: I have  mapped=>false EntityType field.....I press Next and in secont step i can gather this data by adding this method to Flow class and call in Controller

`public function saveUnmappedFields(string $fieldName, FormInterface $form): object
    {
        $unmappedField = $form->get($fieldName)->getData();
        $entity = $form->getData();
        $setterName = 'set'.ucfirst($fieldName);
        $entity->$setterName($unmappedField);

        return $entity;
    }`
    
    But...I press NEXT button to third step and I lost this data because there is not the same formFieldName in second step form
