### ISSUE TITLE
Issue with the example

### ISSUE THREAD

**Issue by pavan168** [craue/CraueFormFlowBundle#71]
I get the following error:

Neither the property "numberOfWheels" nor one of the methods "getNumberOfWheels()", "isNumberOfWheels()", "hasNumberOfWheels()", "__get()" or "__call()" exist and have public access in class "Lucky\RNDBundle\Form\CreateVehicleStep1Form"

**Comment by stefita** [comment]
@pavan168 I want to repeat a step within the flow form. Have you been able to achieve this? It is in your 2. question.
