### ISSUE TITLE
How can I make the "BACK" button save form data?

### ISSUE THREAD

**Issue by lfjeff** [craue/CraueFormFlowBundle#83]
Is there a way to configure things to make the "BACK" button save the form data in a multi-step form?

I have users complaining that the form works fine when they click on "NEXT" but they lose their data when they hit the back button.

**Comment by Adam314** [comment]
I know this is old question but maybe someone will look for answer here.

Clicking "back" resets the next step data. This is done by invalidateStepData() funcion in form flow.

Simple solution is to override this function. Here is my code:

```php
namespace AppBundle\Form;

use Craue\FormFlowBundle\Form\FormFlow;

abstract class CustomFormFlow extends FormFlow
{
    public function invalidateStepData($fromStepNumber) {
        // do nothing, this prevents us from deleting step data when user hits "back" button
    }
}
```

Now create your form flow that extends CustomFormFlow instead of FormFlow.

**Comment by Nairebis** [comment]
Thank you Adam314 for that solution.

Note to Craue: It is *very* non-standard to delete the form data on the page when you do a back button. Honestly, I've never seen it anywhere else, what's the advantage of making the users retype the data? The whole point of the "back" button is to go back and make a correction, not destroy all the subsequent data. If you're filling out a paper form of multiple pages and go back to make a correction, do you throw out all the pages you've already done and re-do them?

I hope you consider fixing this.

**Comment by Filoz** [comment]
Hi, 
I know it's an old question but I need the same behavior.
If I understand correctly the doc, what you (and I) need is to set `$allowDynamicStepNavigation = true;`
because invalidateStepData is called only if this variable is false (and action is go back):
https://github.com/craue/CraueFormFlowBundle/blob/master/Form/FormFlow.php#L670
is it correct?

**Comment by linxlad** [comment]
@Adam314 Not all heroes wear capes. Thanks for that simple solution :+1:

**Comment by linxlad** [comment]
If anyone runs into this issue here is a possible solution:

```
<?php

namespace AppBundle\Form;

use Craue\FormFlowBundle\Form\FormFlow;

/**
 * Class BaseFormType
 * @package OpenObjects\Bundle\CoreBundle\Form
 */
class BaseFlow extends FormFlow
{
    /**
     * If this is set to true then form data for the current
     * step will be saved when transitioning backwards.
     *
     * @var bool
     */
    protected $persistOnBackTransition = false;

    /**
     * @param int $fromStepNumber
     */
    public function invalidateStepData($fromStepNumber)
    {
        // Do nothing, this prevents us from deleting step data when user hits "back" button.
    }

    /**
     * {@inheritdoc}
     */
    protected function bindFlow() {
        parent::bindFlow();

        if ($this->persistOnBackTransition  && $this->getRequestedTransition() === self::TRANSITION_BACK) {
            $currentStepNumber = $this->getCurrentStepNumber() + 1;
            $form = $form = $this->createFormForStep($currentStepNumber);
            $form->setData($this->getFormData());
            $stepData = $this->retrieveStepData();
            $request = $this->getRequest();
            $formName = $form->getName();
            $currentStepData = $request->request->get($formName, []);

            if ($this->handleFileUploads) {
                $currentStepData = array_merge_recursive($currentStepData, $request->files->get($formName, array()));
            }

            $stepData[$currentStepNumber] = $currentStepData;
            $this->saveStepData($stepData);
        }
    }
}
```

**Comment by Filoz** [comment]
@linxlad , this can be a new feature to submit like a pull request... 
I think it will be much appreciated

**Comment by linxlad** [comment]
@Filoz I agree, I am just not sure this is the best way to do. I had to do it this way as the class property $currentStepNumber is private. If it were protected creating a previous method and then save the current step data then calling the next method may have sufficed @craue?

**Comment by linxlad** [comment]
@craue Tested and PR created :)
https://github.com/craue/CraueFormFlowBundle/pull/248

**Comment by Filoz** [comment]
@linù I added a note in the pull request

**Comment by linxlad** [comment]
Is this bundle maintained anymore?
